apiVersion: v1
kind: Service
metadata:
  name: nextblazor-service
  namespace: next # Change the namespace name
spec:
  selector:
    app: nextblazor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 9000
      targetPort: 9000 # Adjust the targetPort as needed for your application
  type: LoadBalancer
