apiVersion: v1
kind: Service
metadata:
  name: nextblazor-service
  namespace: next # Change the namespace name
spec:
  selector:
    app: nextblazor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
