apiVersion: v1
kind: Service
metadata:
  name: nextblazor-service
  namespace: click # Change the namespace name
spec:
  selector:
    app: nextblazor
  ports:
    - name: port-80
      protocol: TCP
      port: 80
      targetPort: 80
    - name: port-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
    - name: port-9000
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer
